models/topic.py
from models import Model
from models.user import User


class Topic(Model):
    @classmethod
    def valid_names(cls):
        names = super().valid_names()
        names = names + [
            ('views', int, 0),
            ('title', str, ''),
            ('content', str, ''),
            ('user_id', str, 0),
            ('board_id', str, 0),
        ]
        return names

    @classmethod
    def find(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def replies(self):
        from .reply import Reply
        ms = Reply.all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.one(id=self.board_id)
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.mail import Mail
from routes import *

from models.reply import Reply
from utils import log

main = Blueprint('reply', __name__)


def users_from_content(content):
    # 不能解决 @在文本中间 比如 123@name abc，这样就不能获得name了
    parts = content.split(' ')
    users = []
    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.one(username=username)
            users.append(u)
    return users


def send_mails(sender, receivers, content):
    for r in receivers:
        form = dict(
            title='你被 {} AT 了'.format(sender.username),
            content=content,
            sender_id=sender.id,
            receiver_id=r.id,
        )
        m = Mail.new(form)
        log(m)


@main.route("/add", methods=["POST"])
def add():
    log('reply add')
    form = request.form
    u = current_user()

    # 发邮件
    log('before send mail', form)
    content = form['content']
    log('reply', content)
    users = users_from_content(content)
    log('reply', users)
    send_mails(u, users, content)
    log('after send mail')

    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *
import json

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = request.args.get('board_id', 'all')
    if board_id == 'all':
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)

    # if r.exists(board_id):
    #     log('hit redis')
    #     json_string = r.get(board_id)
    #     json_list = json.loads(json_string)
    # else:
    #     print('not hit redis')
    #     json_list = []
    #     for m in ms:
    #         j = m.json()
    #         j['replies'] = m.replies()
    #         j['user_image'] = m.user().user_image
    #         json_list.append(j)
    #     json_string = json.dumps(json_list)
    #     r.set(board_id, json_string)
    # ms = json_list

    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id)


@main.route('/<string:id>')
def detail(id):
    m = Topic.one(id=id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/add", methods=["POST"])
# @login_required
@csrf_required
def add():
    form = request.form
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))


@main.route("/delete")
@csrf_required
def delete():
    id = request.args.get('id')
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = request.args.get('board_id')
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>

</head>
<body>
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <a class='brand' href='/'>

          <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg" />

      </a>

      <form id='search_form' class='navbar-search' action="/search">
        <input type='text' id='q' name='q' class='search-query span3' value=''/>
      </form>
      <ul class='nav pull-right'>
        <li><a href='/'>首页</a></li>

        <li>
            <a href='/my/messages'>

              未读消息
            </a>
        </li>

        <li><a href='/getstart'>新手入门</a></li>
        <li><a href='/api'>API</a></li>

        <li><a href="/about" target="">关于</a></li>


        <li><a href='/setting'>设置</a></li>
        <li>
          <a href='/signout' data-method="post" rel="nofollow">退出</a>
        </li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>
{% block main %}{% endblock %}
</body>
</html>

templates/topic/detail.html
{% extends "topic/base.html" %}
{% block title %}
帖子详情 {{ topic.title }}
{% endblock %}
{% block main %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 2 天前
            </span>
                    <span>
                作者
                <a href="/user/hopperhuang">hopperhuang</a>
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 问答
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">
                        {{ topic.content }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        <div class='cell reply_area reply_item'>
            <div class='author_content'>
                <a href="/user/leiwei1991" class="user_avatar">
                    <img src="https://avatars2.githubusercontent.com/u/10721874?v=3&amp;s=120"
                         title="{{ r.user().username }}"/>
                </a>
                <div class='user_info'>
                    <a class='dark reply_author'>
                        {{ r.user().username }}
                    </a>
                    <a class="reply_time">
                        {{ loop.index }}楼 • 2 天前
                    </a>
                </div>
                <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                </div>
            </div>
            <div class='reply_content from-leiwei1991'>
                <div class="markdown-text">
                    {{ r.content }}
                </div>
            </div>
        </div>
        {% endfor %}
        <div>
            <form method="post" action="{{ url_for('reply.add') }}" >
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/topic/index.html
{% extends "topic/base.html" %}
{% block title %}
论坛主页
{% endblock %}
{% block main %}
    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="inner">
                    <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
        </div>
        <div id="content">
            <div class="panel">
                <div class="header">
                    <a href="/topic"
                       class="topic-tab current-tab">
                        全部
                    </a>

                    {% for b in bs %}
                        <a href="/topic?board_id={{ b.id }}"
                           class="topic-tab current-tab">
                            {{ b.title }}
                        </a>
                    {% endfor %}
                </div>
                <div class="inner post">
                    <div class="topic_list">
                        {% for t in ms %}
                            <div class="cell">
                                <div class="topic_title_wrapper">

                                    <a class="user_avatar pull-left">
                                        <img src="{{ t.user().user_image }}" title="avatar"/>
                                    </a>

                                    <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                        {{ t.title }}
                                    </a>
                                    <span>{{ t.replies() | count }} / {{ t.views }}</span>
                                    <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                        删除
                                    </a>

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        (function () {
            var editor = new Editor();
            editor.render($('.editor')[0]);
        })();

    </script>
{% endblock %}

templates/topic/new.html
{% extends "topic/base.html" %}
{% block main %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
                        <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
                            <span class="tab-selector">选择版块：</span>
                            <select name="board_id" id="board" required>
                                {% for b in bs %}
                                    {% if bid == b.id %}
                                        <option value="{{ b.id }}" selected>{{ b.title }}</option>
                                    {% else %}
                                        <option value="{{ b.id }}">{{ b.title }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <div class='markdown_editor in_editor'>
                                <div class='markdown_in_editor'>
                                    <textarea class='editor' name='content' rows='20'
                                              placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                    <div class='editor_buttons'>
                                        <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                               value="提交">
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        (function () {
            var editor = new Editor();
            editor.render($('.editor')[0]);
        })();
    </script>
{% endblock %}

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>